

export const gigs = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Whatever tattooed stumptown art party sriracha gentrify hashtag intelligentsia readymade schlitz brooklyn disrupt." ,
    jobtitle: "Ui Developer",
    username: "Anna Bell",
    post1: "Front-end Developer at JotForm",
    post2: "UI Developer at GitHub",
    post3: "Illustrator at Google",
    post4: "Full-Stack Developer at CodePen",
    post1desc: "Developed front-end for new customer facing end.",
    post2desc: "Developed new conversion funnels and disrupt.",
    post3desc: "Onboarding illustrations for App.",
    post4desc: "Responsible for the encomposing brand expreience.",
    bColor : "rgb(246, 74, 138)",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I can implement scalable and efficient backend solutions for projects. ",
    jobtitle: "Back-end Developer",
    username: "Lannie Coleman",
    post1: "Front-end Developer at JotForm",
    post2: "UI Developer at GitHub",
    post3: "Illustrator at Google",
    post4: "Full-Stack Developer at CodePen",
    post1desc: "I will create ai digital art illustration hyper realistic painting",
    post2desc: "I will create ai digital art illustration hyper realistic painting",
    post3desc: "I will create ai digital art illustration hyper realistic painting",
    post4desc: "I will create ai digital art illustration hyper realistic painting",
    bColor : "#318CE7",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I have experience in developing augmented reality applications for interactive user experiences. ",
    jobtitle: "AR/VR Developer",
    username: "Carol Steve",
    post1: "Front-end Developer at JotForm",
    post2: "UI Developer at GitHub",
    post3: "Illustrator at Google",
    post4: "Full-Stack Developer at CodePen",
    post1desc: "I will create ai digital art illustration hyper realistic painting",
    post2desc: "I will create ai digital art illustration hyper realistic painting",
    post3desc: "I will create ai digital art illustration hyper realistic painting",
    post4desc: "I will create ai digital art illustration hyper realistic painting",
    bColor : "rgb(246, 74, 138)",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Building end-to-end web applications with both frontend and backend components. Designing and developing server-side APIs and database systems. ",
    jobtitle: "Full Stack Developer",
    username: "Don Weber",
    post1: "Front-end Developer at JotForm",
    post2: "UI Developer at GitHub",
    post3: "Backend Developer at Google",
    post4: "Full-Stack Developer at CodePen",
    post1desc: "front-end development for JotForm",
post2desc: "ui/ux design for GitHub official website",
post3desc: "backend development for Google",
post4desc: "full-stack development for CodePen",
    bColor : "#FFBF00",
  },
  // linear-gradient(to right, red,orange,yellow,green,blue,indigo,violet)
  {
    id: 5,
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "Developing machine learning models and algorithms for data analysis and predictions.Implementing artificial intelligence techniques for automated decision-making systems.",
    jobtitle: "AI/ ML Enthusiast",
    username: "Audrey Richards",
    post1: "Front-end Developer at JotForm",
    post2: "UI Developer at GitHub",
    post3: "Illustrator at Google",
    post4: "Full-Stack Developer at CodePen",

    post1desc: "I will create ai digital art illustration hyper realistic painting",
    post2desc: "I will create ai digital art illustration hyper realistic painting",
    post3desc: "I will create ai digital art illustration hyper realistic painting",
    post4desc: "I will create ai digital art illustration hyper realistic painting",
    bColor : "rgb(26, 188, 156)",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai digital art illustration hyper realistic painting",
    jobtitle: "React Developer",
    username: "Walton Shepard ",
    post1: "Front-end Developer at JotForm",
    post2: "UI Developer at GitHub",
    post3: "Illustrator at Google",
    post4: "Full-Stack Developer at CodePen",
    post1desc: "I will create ai digital art illustration hyper realistic painting",
    post2desc: "I will create ai digital art illustration hyper realistic painting",
    post3desc: "I will create ai digital art illustration hyper realistic painting",
    post4desc: "I will create ai digital art illustration hyper realistic painting",
    bColor : "#8F00FF",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will generate images with your prompts using ai dalle",
    jobtitle: "Mobile Developer",
    username: "Waverly Schaefer",
    post1: "Front-end Developer at JotForm",
    post2: "UI Developer at GitHub",
    post3: "Illustrator at Google",
    post4: "Full-Stack Developer at CodePen",
    post1desc: "I will create ai digital art illustration hyper realistic painting",
    post2desc: "I will create ai digital art illustration hyper realistic painting",
    post3desc: "I will create ai digital art illustration hyper realistic painting",
    post4desc: "I will create ai digital art illustration hyper realistic painting",
    bColor : "#FFBF00",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    jobtitle: "Character Art",
    username: "Wilton Hunt",
    post1: "Front-end Developer at JotForm",
    post2: "UI Developer at GitHub",
    post3: "Illustrator at Google",
    post4: "Full-Stack Developer at CodePen",
    post1desc: "I will create ai digital art illustration hyper realistic painting",
    post2desc: "I will create ai digital art illustration hyper realistic painting",
    post3desc: "I will create ai digital art illustration hyper realistic painting",
    post4desc: "I will create ai digital art illustration hyper realistic painting",
    bColor : "#8F00FF",
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    jobtitle: "App Developer",
    username: "Wilton Hunt",
    post1: "Front-end Developer at JotForm",
    post2: "UI Developer at GitHub",
    post3: "Illustrator at Google",
    post4: "Full-Stack Developer at CodePen",
    post1desc: "I will create ai digital art illustration hyper realistic painting",
    post2desc: "I will create ai digital art illustration hyper realistic painting",
    post3desc: "I will create ai digital art illustration hyper realistic painting",
    post4desc: "I will create ai digital art illustration hyper realistic painting",
    bColor : "#318CE7",
  }
];